"""Component classification (§9 Dependency ≠ Upstream Source ≠ Vendored Code).

This module runs *before* any similarity is computed, and it is the single most
load-bearing correctness property in the provenance engine. A repository that
vendors 40 000 ``node_modules`` files is not "mostly upstream" — those files were
never authored by anyone in the portfolio and were never authored by the upstream
either. Letting them into a denominator produces exactly the confident, wrong
answer §29 forbids ("依賴不被誤判為上游來源").

So classification is structural and evidence-based, and the default for content we
cannot place is :data:`ComponentClass.UNKNOWN`, never ``ORIGINAL``. The engine only
promotes UNKNOWN to ORIGINAL once it has established that no upstream exists
(axiom 4: absence of a known source is not proof of authorship).
"""

from __future__ import annotations

import posixpath
from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping

from ..config import AnalysisConfig
from ..models import ComponentProfile
from ..taxonomy import ComponentClass, ContributionDimension

# --------------------------------------------------------------------------
# structural vocabularies
# --------------------------------------------------------------------------

#: Directories that hold *resolved third-party packages*. Their contents belong to
#: neither this repository nor its upstream — they belong to a package registry.
DEPENDENCY_DIRS: frozenset[str] = frozenset(
    {
        "node_modules",
        ".venv",
        "venv",
        "env",
        "site-packages",
        "bower_components",
        "jspm_packages",
        "pods",
        ".pnpm",
        ".pnpm-store",
        ".yarn",
        "godeps",
        "packages",  # NuGet / paket restore output
        ".bundle",
        ".gradle",
        ".cargo",
        ".pub-cache",
    }
)

#: Directories that hold *copied upstream source*. Same code, different governance:
#: vendored content is inside the repository's own history and can be modified,
#: so §9.2 requires it to be tracked, not merely dropped.
VENDORED_DIRS: frozenset[str] = frozenset(
    {
        "vendor",
        "vendored",
        "third_party",
        "thirdparty",
        "3rdparty",
        "3rd_party",
        "external",
        "externals",
        "extern",
        "deps",
        "submodules",
    }
)

#: Build products and machine-written trees.
GENERATED_DIRS: frozenset[str] = frozenset(
    {
        "dist",
        "build",
        "out",
        "output",
        "target",
        "generated",
        "__generated__",
        "gen",
        "coverage",
        ".cache",
        ".next",
        ".nuxt",
        ".svelte-kit",
        ".parcel-cache",
        ".turbo",
        "_site",
        "public/build",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        ".ruff_cache",
        "obj",
        "bin",
    }
)

#: Exact file names that are machine-written even when they sit at the repo root.
GENERATED_FILES: frozenset[str] = frozenset(
    {
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "npm-shrinkwrap.json",
        "poetry.lock",
        "pdm.lock",
        "uv.lock",
        "cargo.lock",
        "composer.lock",
        "gemfile.lock",
        "go.sum",
        "packages.lock.json",
        "flake.lock",
        "podfile.lock",
        "mix.lock",
    }
)

#: Suffix patterns that mark a file as compiled, minified or code-generated.
GENERATED_SUFFIXES: tuple[str, ...] = (
    ".min.js",
    ".min.css",
    ".map",
    ".bundle.js",
    ".chunk.js",
    "_pb2.py",
    "_pb2_grpc.py",
    ".pb.go",
    ".pb.cc",
    ".pb.h",
    ".g.dart",
    ".freezed.dart",
    ".designer.cs",
    ".generated.ts",
    "_generated.go",
)

#: First-N-bytes markers some generators emit. Checked only when file text is
#: available (deep mode); the shallow path relies on paths and names alone.
GENERATED_MARKERS: tuple[str, ...] = (
    "@generated",
    "code generated by",
    "auto-generated",
    "autogenerated",
    "do not edit",
    "this file is generated",
    "generated by protoc",
)

BINARY_EXTENSIONS: frozenset[str] = frozenset(
    {
        ".zip", ".gz", ".tar", ".tgz", ".bz2", ".xz", ".7z", ".rar", ".jar", ".war",
        ".exe", ".dll", ".so", ".dylib", ".a", ".lib", ".o", ".obj", ".class",
        ".pyc", ".pyd", ".wasm", ".bin", ".dat", ".db", ".sqlite", ".sqlite3",
        ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx", ".odt",
        ".pack", ".idx", ".node", ".dmg", ".msi", ".deb", ".rpm", ".apk",
    }
)

ASSET_EXTENSIONS: frozenset[str] = frozenset(
    {
        ".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp", ".ico", ".svg", ".avif",
        ".mp3", ".wav", ".ogg", ".flac", ".m4a", ".mp4", ".webm", ".mov", ".avi",
        ".ttf", ".otf", ".woff", ".woff2", ".eot",
        ".psd", ".ai", ".sketch", ".fig", ".blend", ".fbx", ".obj3d", ".glb", ".gltf",
    }
)

DOC_EXTENSIONS: frozenset[str] = frozenset({".md", ".rst", ".txt", ".adoc", ".org", ".mdx"})

TEST_DIR_NAMES: frozenset[str] = frozenset({"test", "tests", "spec", "specs", "__tests__", "testing", "e2e"})
DOC_DIR_NAMES: frozenset[str] = frozenset({"doc", "docs", "documentation", "wiki", "manual", "papers"})
UI_DIR_NAMES: frozenset[str] = frozenset({"ui", "components", "views", "pages", "templates", "styles", "css", "theme"})
DATA_DIR_NAMES: frozenset[str] = frozenset({"models", "schema", "schemas", "migrations", "entities", "db", "data"})
DEPLOY_DIR_NAMES: frozenset[str] = frozenset({"deploy", "deployment", "infra", "infrastructure", "terraform", "helm", "k8s", "kubernetes", ".github", ".circleci", "ci"})
RESEARCH_DIR_NAMES: frozenset[str] = frozenset({"research", "notebooks", "experiments", "analysis", "whitepaper", "whitepapers"})

#: Dependency manifests. Their *presence* separates ORIGINAL from
#: ORIGINAL_WITH_DEPENDENCIES (§6.2) — a manifest is a declaration of dependency,
#: which §9.1 says is emphatically not a declaration of upstream ancestry.
DEPENDENCY_MANIFESTS: frozenset[str] = frozenset(
    {
        "package.json",
        "pyproject.toml",
        "requirements.txt",
        "requirements.in",
        "setup.py",
        "setup.cfg",
        "pipfile",
        "environment.yml",
        "cargo.toml",
        "go.mod",
        "composer.json",
        "gemfile",
        "build.gradle",
        "build.gradle.kts",
        "pom.xml",
        "pubspec.yaml",
        "mix.exs",
        "deno.json",
        "bun.lockb",
        "cmakelists.txt",
        "package.swift",
    }
)

LOCK_FILES: frozenset[str] = GENERATED_FILES

#: Classes excluded from every contribution denominator (§8.2 "目前有效內容").
NON_EFFECTIVE_CLASSES: frozenset[ComponentClass] = frozenset(
    {
        ComponentClass.DEPENDENCY,
        ComponentClass.VENDORED,
        ComponentClass.VENDORED_MODIFIED,
        ComponentClass.GENERATED,
        ComponentClass.BINARY,
    }
)


# --------------------------------------------------------------------------
# results
# --------------------------------------------------------------------------

@dataclass(slots=True)
class ClassifiedFile:
    path: str
    component_class: ComponentClass
    size: int
    reason: str
    dimension: ContributionDimension | None = None


@dataclass(slots=True)
class ComponentSummary:
    """Aggregated §9.3 view of a repository tree.

    ``effective_*`` is the denominator §8.2 calls "目前有效內容": everything that a
    human plausibly authored or curated, with packages, build output and binaries
    removed.
    """

    files: list[ClassifiedFile] = field(default_factory=list)
    total_files: int = 0
    total_bytes: int = 0
    effective_files: int = 0
    effective_bytes: int = 0
    files_by_class: dict[ComponentClass, int] = field(default_factory=dict)
    bytes_by_class: dict[ComponentClass, int] = field(default_factory=dict)
    files_by_dimension: dict[ContributionDimension, int] = field(default_factory=dict)
    bytes_by_dimension: dict[ContributionDimension, int] = field(default_factory=dict)
    excluded_roots: list[str] = field(default_factory=list)
    dependency_manifests: list[str] = field(default_factory=list)
    lock_files: list[str] = field(default_factory=list)
    license_files: list[str] = field(default_factory=list)
    attribution_files: list[str] = field(default_factory=list)
    embedded_license_files: list[str] = field(default_factory=list)
    submodule_declared: bool = False

    # -- ratios ---------------------------------------------------------

    def share_of_files(self, component_class: ComponentClass) -> float:
        return self.files_by_class.get(component_class, 0) / self.total_files if self.total_files else 0.0

    def share_of_bytes(self, component_class: ComponentClass) -> float:
        return self.bytes_by_class.get(component_class, 0) / self.total_bytes if self.total_bytes else 0.0

    @property
    def effective_file_ratio(self) -> float:
        """How much of the tree survives the §9.2 exclusions, by file count."""
        return self.effective_files / self.total_files if self.total_files else 0.0

    @property
    def vendored_files(self) -> int:
        return self.files_by_class.get(ComponentClass.VENDORED, 0) + self.files_by_class.get(
            ComponentClass.VENDORED_MODIFIED, 0
        )

    @property
    def dependency_files(self) -> int:
        return self.files_by_class.get(ComponentClass.DEPENDENCY, 0)

    @property
    def generated_files(self) -> int:
        return self.files_by_class.get(ComponentClass.GENERATED, 0)

    def effective_paths(self) -> list[str]:
        return [f.path for f in self.files if f.component_class not in NON_EFFECTIVE_CLASSES]

    # -- persistence ----------------------------------------------------

    def to_profiles(self, *, max_rows: int = 200) -> list[ComponentProfile]:
        """Roll per-file classifications up into storable :class:`ComponentProfile` rows.

        Per-file rows would be tens of thousands for a vendored repository, so files
        are grouped by (component root, class). The grouping key is the excluded
        directory when there is one, otherwise the top-level path segment — which is
        exactly the granularity a human reviewer reasons about.
        """
        buckets: dict[tuple[str, ComponentClass], dict[str, Any]] = {}
        for item in self.files:
            root = _component_root(item.path, item.component_class)
            key = (root, item.component_class)
            bucket = buckets.setdefault(key, {"bytes": 0, "files": 0, "reason": item.reason})
            bucket["bytes"] += item.size
            bucket["files"] += 1
        rows = [
            ComponentProfile(
                path=path,
                component_class=component_class,
                bytes=data["bytes"],
                files=data["files"],
                reason=data["reason"],
            )
            for (path, component_class), data in buckets.items()
        ]
        rows.sort(key=lambda r: (-r.files, r.path))
        return rows[:max_rows]


# --------------------------------------------------------------------------
# classification
# --------------------------------------------------------------------------

def _component_root(path: str, component_class: ComponentClass) -> str:
    parts = path.split("/")
    if component_class in NON_EFFECTIVE_CLASSES:
        # Report the deepest recognised exclusion root, e.g. "web/node_modules".
        for index, part in enumerate(parts[:-1]):
            lowered = part.lower()
            if lowered in DEPENDENCY_DIRS or lowered in VENDORED_DIRS or lowered in GENERATED_DIRS:
                return "/".join(parts[: index + 1])
    return parts[0] if len(parts) > 1 else "."


def _normalize_entry(entry: Any) -> tuple[str, int, str] | None:
    """Accept GitHub tree entries, ``(path, size)`` pairs, or bare paths."""
    if isinstance(entry, Mapping):
        if entry.get("type") not in (None, "blob"):
            return None  # trees and commits (submodule gitlinks) carry no content
        path = str(entry.get("path") or "")
        return (path, int(entry.get("size") or 0), str(entry.get("mode") or "")) if path else None
    if isinstance(entry, (tuple, list)) and len(entry) >= 2:
        return str(entry[0]), int(entry[1]), ""
    if isinstance(entry, str):
        return entry, 0, ""
    return None


def _dimension_for(path: str) -> ContributionDimension:
    """Map a path onto a §8.3 contribution dimension. Heuristic, and only used to
    describe *where* work sits — never to decide whether work happened."""
    lowered = path.lower()
    parts = lowered.split("/")
    name = parts[-1]
    _, ext = posixpath.splitext(name)

    if any(part in TEST_DIR_NAMES for part in parts[:-1]) or name.startswith("test_") or "_test." in name or ".test." in name or ".spec." in name:
        return ContributionDimension.TESTS
    if any(part in DEPLOY_DIR_NAMES for part in parts[:-1]) or name in {"dockerfile", "makefile", "procfile", "wrangler.toml", "vercel.json", "netlify.toml"}:
        return ContributionDimension.DEPLOYMENT
    if any(part in DOC_DIR_NAMES for part in parts[:-1]) or ext in DOC_EXTENSIONS:
        return ContributionDimension.DOCUMENTATION
    if any(part in RESEARCH_DIR_NAMES for part in parts[:-1]) or ext == ".ipynb":
        return ContributionDimension.RESEARCH
    if ext in ASSET_EXTENSIONS:
        return ContributionDimension.ASSETS
    if any(part in UI_DIR_NAMES for part in parts[:-1]) or ext in {".css", ".scss", ".less", ".html", ".vue", ".svelte", ".jsx", ".tsx"}:
        return ContributionDimension.UI_UX
    if any(part in DATA_DIR_NAMES for part in parts[:-1]) or ext in {".sql", ".prisma", ".graphql", ".proto"}:
        return ContributionDimension.DATA_MODEL
    if ext in {".json", ".yaml", ".yml", ".toml", ".csv", ".xml"}:
        return ContributionDimension.CONTENT
    return ContributionDimension.CODE


def _classify_one(
    path: str,
    size: int,
    mode: str,
    *,
    dependency_dirs: frozenset[str],
    vendored_dirs: frozenset[str],
    generated_dirs: frozenset[str],
    default_class: ComponentClass,
) -> tuple[ComponentClass, str]:
    parts = path.split("/")
    name = parts[-1].lower()
    directories = [p.lower() for p in parts[:-1]]

    # §9.2 exclusions win over everything else: a minified bundle inside
    # node_modules is a dependency, not "generated local work".
    for directory in directories:
        if directory in dependency_dirs:
            return ComponentClass.DEPENDENCY, f"under dependency directory '{directory}/' (§9.2)"
    for directory in directories:
        if directory in vendored_dirs:
            return ComponentClass.VENDORED, f"under vendored directory '{directory}/' (§9.2)"
    for index, directory in enumerate(directories):
        if directory in generated_dirs or "/".join(directories[: index + 1]) in generated_dirs:
            return ComponentClass.GENERATED, f"under build/generated directory '{directory}/' (§9.2)"

    if name in GENERATED_FILES:
        return ComponentClass.GENERATED, "lock file — written by a package manager"
    if any(name.endswith(suffix) for suffix in GENERATED_SUFFIXES):
        return ComponentClass.GENERATED, "file name marks compiled or generated output"

    _, ext = posixpath.splitext(name)
    if ext in BINARY_EXTENSIONS:
        return ComponentClass.BINARY, f"binary extension '{ext}'"
    if ext in ASSET_EXTENSIONS:
        return ComponentClass.ASSET, f"asset extension '{ext}'"
    if mode == "160000":
        return ComponentClass.VENDORED, "git submodule gitlink"

    return default_class, "no exclusion matched"


def classify_paths(
    entries: Iterable[Any],
    *,
    config: AnalysisConfig | None = None,
    default_class: ComponentClass = ComponentClass.UNKNOWN,
    extra_excluded_dirs: Iterable[str] = (),
) -> ComponentSummary:
    """Classify every path in a repository tree (§9.3).

    ``entries`` accepts GitHub ``git/trees`` items, ``(path, size)`` pairs, or bare
    path strings. ``default_class`` stays :data:`ComponentClass.UNKNOWN` unless the
    caller has *positively established* there is no upstream — see the module
    docstring on why the default is not ``ORIGINAL``.
    """
    cfg = config or AnalysisConfig()
    configured = {d.strip("/").lower() for d in cfg.excluded_dirs} | {
        d.strip("/").lower() for d in extra_excluded_dirs
    }
    # The configured exclusion list is a flat set; split it back into the three
    # semantically different families so a `vendor/` hit is not reported as a
    # dependency (§9.1 keeps these strictly apart).
    dependency_dirs = DEPENDENCY_DIRS | (configured & DEPENDENCY_DIRS)
    vendored_dirs = VENDORED_DIRS | (configured & VENDORED_DIRS)
    generated_dirs = GENERATED_DIRS | (configured - DEPENDENCY_DIRS - VENDORED_DIRS)

    summary = ComponentSummary()
    excluded_roots: set[str] = set()

    for raw in entries:
        normalized = _normalize_entry(raw)
        if normalized is None:
            continue
        path, size, mode = normalized
        component_class, reason = _classify_one(
            path,
            size,
            mode,
            dependency_dirs=dependency_dirs,
            vendored_dirs=vendored_dirs,
            generated_dirs=generated_dirs,
            default_class=default_class,
        )
        dimension = _dimension_for(path) if component_class not in NON_EFFECTIVE_CLASSES else None
        summary.files.append(ClassifiedFile(path, component_class, size, reason, dimension))

        summary.total_files += 1
        summary.total_bytes += size
        summary.files_by_class[component_class] = summary.files_by_class.get(component_class, 0) + 1
        summary.bytes_by_class[component_class] = summary.bytes_by_class.get(component_class, 0) + size

        if component_class in NON_EFFECTIVE_CLASSES:
            excluded_roots.add(_component_root(path, component_class))
        else:
            summary.effective_files += 1
            summary.effective_bytes += size
            if dimension is not None:
                summary.files_by_dimension[dimension] = summary.files_by_dimension.get(dimension, 0) + 1
                summary.bytes_by_dimension[dimension] = summary.bytes_by_dimension.get(dimension, 0) + size

        _record_special_file(summary, path, component_class)

    summary.excluded_roots = sorted(excluded_roots)
    return summary


def _record_special_file(summary: ComponentSummary, path: str, component_class: ComponentClass) -> None:
    """Note manifests, licences and attribution files wherever they appear.

    Deliberately runs for excluded paths too: a ``LICENSE`` sitting inside
    ``vendor/`` is the single most important licence signal in §10, and dropping it
    with the rest of the vendored tree would hide a copyleft trigger.
    """
    name = path.split("/")[-1].lower()
    stem = posixpath.splitext(name)[0]
    directories = [p.lower() for p in path.split("/")[:-1]]
    # "Inside an excluded directory", not "has a non-effective class": a lock file
    # at the repository root is GENERATED but its manifest neighbourhood still
    # matters, whereas a manifest inside node_modules describes someone else's package.
    inside_excluded = any(
        d in DEPENDENCY_DIRS or d in VENDORED_DIRS or d in GENERATED_DIRS for d in directories
    )

    if name in DEPENDENCY_MANIFESTS and not inside_excluded:
        summary.dependency_manifests.append(path)
    if name in LOCK_FILES and not inside_excluded:
        summary.lock_files.append(path)
    if stem in {"license", "licence", "copying", "copyright", "unlicense"}:
        if inside_excluded or "/" in path:
            summary.embedded_license_files.append(path)
        else:
            summary.license_files.append(path)
    if stem in {"notice", "authors", "contributors", "credits", "acknowledgements", "acknowledgments", "third_party_notices", "third-party-notices"}:
        summary.attribution_files.append(path)
    if name == ".gitmodules":
        summary.submodule_declared = True
